/**
 * Icon resolution for server components only.
 *
 * `data.ts` refers to icons by key so that client bundles never import
 * react-icons or lucide. Server components call `getIcon(key)` and render the
 * SVG into the HTML; the client receives markup, not JavaScript.
 */
import type { ComponentType, SVGProps } from "react";
import {
  SiPhp,
  SiJavascript,
  SiTypescript,
  SiPython,
  SiOpenjdk,
  SiSharp,
  SiCplusplus,
  SiGo,
  SiRust,
  SiKotlin,
  SiSwift,
  SiDart,
  SiHtml5,
  SiCss,
  SiReact,
  SiNextdotjs,
  SiVuedotjs,
  SiAngular,
  SiLaravel,
  SiCodeigniter,
  SiNodedotjs,
  SiExpress,
  SiNestjs,
  SiDotnet,
  SiFlutter,
  SiElectron,
  SiMysql,
  SiMariadb,
  SiPostgresql,
  SiMongodb,
  SiRedis,
  SiSqlite,
  SiFirebase,
  SiSupabase,
  SiDocker,
  SiLinux,
  SiUbuntu,
  SiNginx,
  SiApache,
  SiGit,
  SiGithub,
  SiGitlab,
  SiVercel,
  SiCloudflare,
  SiDigitalocean,
  SiOpenai,
  SiInstagram,
} from "react-icons/si";
import {
  Database,
  Cloud,
  CloudCog,
  Workflow,
  Bot,
  MessagesSquare,
  Wand2,
  Globe2,
  BrainCircuit,
  Cpu,
  Code2,
  Smartphone,
  Server,
  ShieldCheck,
  GitBranch,
  Boxes,
  Layers,
  Rocket,
  Compass,
  PencilRuler,
  Hammer,
  TestTube2,
  CloudUpload,
  Wrench,
  Mail,
  Phone,
} from "lucide-react";

export type IconComponent = ComponentType<SVGProps<SVGSVGElement>>;

const icons: Record<string, IconComponent> = {
  php: SiPhp,
  javascript: SiJavascript,
  typescript: SiTypescript,
  python: SiPython,
  java: SiOpenjdk,
  csharp: SiSharp,
  cplusplus: SiCplusplus,
  go: SiGo,
  rust: SiRust,
  kotlin: SiKotlin,
  swift: SiSwift,
  dart: SiDart,
  html5: SiHtml5,
  css: SiCss,
  react: SiReact,
  nextjs: SiNextdotjs,
  vue: SiVuedotjs,
  angular: SiAngular,
  laravel: SiLaravel,
  codeigniter: SiCodeigniter,
  nodejs: SiNodedotjs,
  express: SiExpress,
  nestjs: SiNestjs,
  dotnet: SiDotnet,
  flutter: SiFlutter,
  electron: SiElectron,
  mysql: SiMysql,
  mariadb: SiMariadb,
  postgresql: SiPostgresql,
  mongodb: SiMongodb,
  redis: SiRedis,
  sqlite: SiSqlite,
  firebase: SiFirebase,
  supabase: SiSupabase,
  docker: SiDocker,
  linux: SiLinux,
  ubuntu: SiUbuntu,
  nginx: SiNginx,
  apache: SiApache,
  git: SiGit,
  github: SiGithub,
  gitlab: SiGitlab,
  vercel: SiVercel,
  cloudflare: SiCloudflare,
  digitalocean: SiDigitalocean,
  openai: SiOpenai,
  instagram: SiInstagram,
  database: Database as unknown as IconComponent,
  cloud: Cloud as unknown as IconComponent,
  cloudcog: CloudCog as unknown as IconComponent,
  workflow: Workflow as unknown as IconComponent,
  bot: Bot as unknown as IconComponent,
  messages: MessagesSquare as unknown as IconComponent,
  wand: Wand2 as unknown as IconComponent,
  globe: Globe2 as unknown as IconComponent,
  brain: BrainCircuit as unknown as IconComponent,
  cpu: Cpu as unknown as IconComponent,
  code: Code2 as unknown as IconComponent,
  smartphone: Smartphone as unknown as IconComponent,
  server: Server as unknown as IconComponent,
  shield: ShieldCheck as unknown as IconComponent,
  gitbranch: GitBranch as unknown as IconComponent,
  boxes: Boxes as unknown as IconComponent,
  layers: Layers as unknown as IconComponent,
  rocket: Rocket as unknown as IconComponent,
  compass: Compass as unknown as IconComponent,
  ruler: PencilRuler as unknown as IconComponent,
  hammer: Hammer as unknown as IconComponent,
  testtube: TestTube2 as unknown as IconComponent,
  cloudupload: CloudUpload as unknown as IconComponent,
  wrench: Wrench as unknown as IconComponent,
  mail: Mail as unknown as IconComponent,
  phone: Phone as unknown as IconComponent,
};

export function getIcon(key: string): IconComponent {
  const icon = icons[key];
  if (!icon) throw new Error(`Unknown icon key: ${key}`);
  return icon;
}
