import puppeteer from "puppeteer";
const b = await puppeteer.launch({executablePath:"/opt/pw-browsers/chromium-1194/chrome-linux/chrome",args:["--no-sandbox","--use-gl=angle","--use-angle=swiftshader","--enable-unsafe-swiftshader"]});
const p = await b.newPage();
await p.setViewport({width:1440,height:900});
p.on("pageerror", e => console.log("PAGEERROR", e.message, "\n", e.stack?.split("\n").slice(0,6).join("\n")));
p.on("console", m => { if (m.type()==="error"||m.type()==="warning") console.log(m.type(), m.text()); });
await p.goto("http://localhost:3000/",{waitUntil:"networkidle0"});
await new Promise(r=>setTimeout(r,6000));
const log = await p.evaluate(()=>document.querySelector(".boot")?.innerText);
console.log("BOOT:", log);
console.log("gl class:", await p.evaluate(()=>document.documentElement.className));
console.log("canvas:", await p.evaluate(()=>!!document.querySelector("canvas")));
await b.close();
