/**
 * Build-time embedding of this site's own source code and git history.
 *
 * Runs as `prebuild`. It reads a curated list of files from the repo and this
 * repository's real `git log --oneline --graph`, and writes them as string
 * constants to `src/experience/os/sources.generated.ts` so the in-site code
 * editor and terminal show the truth, not a mock. The generated file is
 * committed so a fresh clone type-checks before its first build.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { execSync } from "node:child_process";
import path from "node:path";

const root = path.resolve(new URL(".", import.meta.url).pathname, "..");

const FILES = [
  "src/lib/data.ts",
  "src/lib/acts.ts",
  "src/lib/store.ts",
  "src/app/layout.tsx",
  "src/experience/rig/CameraRig.tsx",
  "src/experience/rig/keyframes.ts",
  "src/experience/desk/Keyboard.tsx",
  "src/experience/desk/shaders/window.ts",
  "src/experience/os/Terminal.ts",
  "src/experience/effects/DiveEffect.ts",
  "scripts/embed-sources.mjs",
];

const MAX_LINES = 420;

const files = FILES.map((rel) => {
  let text = "";
  try {
    text = readFileSync(path.join(root, rel), "utf8");
  } catch {
    text = `// ${rel} is not part of this build yet\n`;
  }
  const lines = text.split("\n");
  const clipped = lines.length > MAX_LINES;
  const body = (clipped ? lines.slice(0, MAX_LINES) : lines).join("\n");
  return { path: rel, lines: lines.length, clipped, text: body };
});

let gitLog = "";
let gitHead = "";
try {
  gitLog = execSync("git log --oneline --graph --decorate=short -n 24", {
    cwd: root,
    encoding: "utf8",
  }).trimEnd();
  gitHead = execSync("git rev-parse --short HEAD", { cwd: root, encoding: "utf8" }).trim();
} catch {
  // keep whatever was generated last time
  try {
    const prev = readFileSync(path.join(root, "src/experience/os/sources.generated.ts"), "utf8");
    const m = prev.match(/export const GIT_LOG = (".*?");\nexport const GIT_HEAD = (".*?");/s);
    if (m) {
      gitLog = JSON.parse(m[1]);
      gitHead = JSON.parse(m[2]);
    }
  } catch {
    gitLog = "* (no git history available at build time)";
    gitHead = "unknown";
  }
}

const out = `/* eslint-disable */
// GENERATED by scripts/embed-sources.mjs — do not edit. Regenerated on every build.
// Contains this site's own source files and its real git history.

export interface SourceFile {
  path: string;
  lines: number;
  clipped: boolean;
  text: string;
}

export const SOURCES: SourceFile[] = ${JSON.stringify(files, null, 2)};

export const GIT_LOG = ${JSON.stringify(gitLog)};
export const GIT_HEAD = ${JSON.stringify(gitHead)};
export const GENERATED_AT = ${JSON.stringify(new Date().toISOString())};
`;

writeFileSync(path.join(root, "src/experience/os/sources.generated.ts"), out);
console.log(`embedded ${files.length} source files, git head ${gitHead}`);
